"""Added gemini resume analyzer fields

Revision ID: f70181dc97ca
Revises: 05e8297d7945
Create Date: 2026-04-14 23:08:53.341578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70181dc97ca'
down_revision = '05e8297d7945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projects_detected', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('experience_level')
        batch_op.drop_column('projects_detected')

    # ### end Alembic commands ###
